[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'rking/ag.vim'
