[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'vim-scripts/twilight'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/vimproc'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'othree/yajs.vim'
