[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

### git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

### カラースキーム
[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'thinca/vim-quickrun'

### table
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

### ファイル検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

### grep
[[plugins]]
repo = 'rking/ag.vim'

### コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'twitvim/twitvim'

### git command
[[plugins]]
repo = 'tpope/vim-fugitive'

### 非同期syntax check
[[plugins]]
repo = 'w0rp/ale'

### マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo= 'easymotion/vim-easymotion'

[[plugins]]
repo= 'y-ono366/csv-2-sql-vim'

[[plugins]]
repo= 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo ='idanarye/vim-merginal'

[[plugins]]
repo = 'tmhedberg/matchit'
