[[plugins]]
repo = 'scrooloose/nerdtree'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/quickrun.lvim'
'''
on_cmd = ['QuickRun']

### table
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/table-mode.lvim'
'''
on_i = 1

### コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/tcomment_vim.lvim'
'''
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo= 'vim-jp/vimdoc-ja'

### golang
[[plugins]]
repo = 'fatih/vim-go'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/vim-go.lvim'
'''
on_ft = ['go']
