[[plugins]]
repo = 'Shougo/dein.vim'

### カラースキーム
[[plugins]]
repo = 'morhetz/gruvbox'


### table
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

### コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

### grep
###[[plugins]]
###repo = 'rking/ag.vim'

[[plugins]]
repo = 'y-ono366/twitvim'

### 非同期syntax check
[[plugins]]
repo = 'w0rp/ale'

### マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo= 'easymotion/vim-easymotion'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo ='idanarye/vim-merginal'

[[plugins]]
repo = 'tmhedberg/matchit'

###fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo= 'vim-jp/vimdoc-ja'

### git command
[[plugins]]
repo = 'tpope/vim-fugitive'
