[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/quickrun.lvim'
'''

### table
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/table-mode.lvim'
'''

### コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/tcomment_vim.lvim'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo= 'vim-jp/vimdoc-ja'
