[[plugins]]
repo = 'scrooloose/nerdtree'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/quickrun.lvim'
'''
on_cmd = ['QuickRun']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']


### golang
[[plugins]]
repo = 'fatih/vim-go'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/vim-go.lvim'
'''
on_ft = ['go']


### git command
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_post_source = '''
    exe 'source ~/dotfiles/vim/etc/modules/fugitive.lvim'
'''
on_cmd = ['Gst']
