[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree']

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = 'source ~/dotfiles/vim/etc/modules/quickrun.lvim'
on_cmd = ['QuickRun']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','gohtmltmpl']


### golang
[[plugins]]
repo = 'fatih/vim-go'
hook_post_source = 'source ~/dotfiles/vim/etc/modules/vim-go.lvim'
on_ft = ['go']

###vue syntax
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = 'source ~/dotfiles/vim/etc/modules/accelerated_jk.lvim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = {n ='<Plug>'}
hook_add = 'source ~/dotfiles/vim/etc/modules/anzu.lvim'
