[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

### git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

### カラースキーム
[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'gregsexton/MatchTag'

### ES6 SyntaxHighLight
[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

### table
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'pangloss/vim-javascript'

### ファイル検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

### grep
[[plugins]]
repo = 'rking/ag.vim'

### コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'

### PUG syntax
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'twitvim/twitvim'

[[plugins]]
repo = 'udalov/kotlin-vim'

### git command
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
